const GAME_WON = 'GAME_WON'
const RESET_HAS_WON = 'RESET_HAS_WON'
const GAME_TIME = 'GAME_TIME'
const GAME_LOST = 'GAME_LOST'
const GAME_PARAMS = 'GAME_PARAMS'
const GENERATE_BOARD = 'GENERATE_BOARD'
const UPDATE_BOARD = 'UPDATE_BOARD'

export default {
  GAME_LOST,
  GAME_PARAMS,
  GAME_TIME,
  GAME_WON,
  GENERATE_BOARD,
  RESET_HAS_WON,
  UPDATE_BOARD
}